version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432" 
    volumes:
      - postgres_catalog:/var/lib/docker/volumes/postgres_catalog/_data


volumes:
  postgres_catalog:
