global using BuildingBlocks.CQRS;
global using Mapster;
global using MediatR;
global using Carter;
global using Marten;
global using FluentValidation;
global using BuildingBlocks.Behaviour;
global using BuildingBlocks.Exceptions;
global using BuildingBlocks.Behavior;
